# Version of the Icarus theme that is currently used
version: 2.0.0
# Path or URL to the website's icon
favicon: https://drive.google.com/uc?export=download&id=1O6kDxxDKRUJoO2l7a63UrH6pwBPg4iYM
# Path or URL to RSS atom.xml
rss: 
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo: https://drive.google.com/uc?export=download&id=1pD5zVq2kD5LvJwqy7jcsGiDY3xXwAW09
# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
    # Facebook App ID
    fb_app_id: 
    # Facebook Admin ID
    fb_admins: 
    # Twitter ID
    twitter_id: 
    # Twitter site
    twitter_site: 
    # Google+ profile link
    google_plus: 
# Navigation bar link settings
navbar:
    # Navigation bar menu links
    menu:
        Blog: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    # Navigation bar links to be shown on the right

# Footer section link settings
footer:
    # Links to be shown on the right of the footer section
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/MeowLucian/MeowLucian.github.io_Hexo_Theme'
# Article display settings
article:
    # Code highlight theme (https://github.com/highlightjs/highlight.js/tree/master/src/styles)
    highlight: atom-one-light
    # Whether to show article thumbnail images
    thumbnail: true
    # Whether to show estimate article reading time
    readtime: true
# Search plugin settings (http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Search-Plugins)
search:
    # Name of the search plugin
    type: insight
# Comment plugin settings (http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Comment-Plugins)
comment:
    # Name of the comment plugin
    type: disqus
    shortname: braingarden
# Share plugin settings (http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Share-Plugins)
share:
    # Share plugin name
    type: 
# Sidebar widget settings (http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/)
widgets:
    -
        type: profile
        position: left
        author: Meow Lucian
        author_title: Engineer
        location: Hsinchu, Taiwan
        avatar: https://drive.google.com/uc?export=download&id=1_hpo3Bm18dspxCcXA0dMxyTaC5SIBzrS
        gravatar: 
        follow_link: 'http://github.com/MeowLucian'
        social_links:
            Github:
                icon: fab fa-github
                url: 'http://github.com/MeowLucian'
            Facebook:
                icon: fab fa-facebook
                url: 'https://www.facebook.com/profile.php?id=100002550282519'
            Linkedin:
                icon: fab fa-linkedin
                url: 'https://www.linkedin.com/in/%E4%BB%95%E5%AE%89-%E7%BE%85-505a02132/'
    -
        type: toc
        position: left
    -
        type: links
        position: left
    -
        type: category
        position: left
    -
        type: tagcloud
        position: left
    -
        type: recent_posts
        position: right
    -
        type: archive
        position: right
    -
        type: tag
        position: right
# Other plugin settings
plugins:
    # Enable page animations
    animejs: true
    # Enable the lightGallery and Justified Gallery plugins (http://ppoffice.github.io/hexo-theme-icarus/2016/07/08/plugin/Gallery/)
    gallery: true
    # Enable the Outdated Browser plugin (http://outdatedbrowser.com/)
    outdated-browser: true
    # Enable the MathJax plugin (http://ppoffice.github.io/hexo-theme-icarus/2018/01/01/plugin/MathJax/)
    mathjax: true
    # Show the back to top button on mobile devices
    back-to-top: true
    # Google Analytics plugin settings (http://ppoffice.github.io/hexo-theme-icarus/2018/01/01/plugin/Analytics/#Google-Analytics)
    google-analytics:
        # Google Analytics tracking id
        tracking_id: 
    # Baidu Analytics plugin settings (http://ppoffice.github.io/hexo-theme-icarus/2018/01/01/plugin/Analytics/#Baidu-Analytics)
    baidu-analytics:
        # Baidu Analytics tracking id
        tracking_id: 
    # Hotjar user feedback plugin (http://ppoffice.github.io/hexo-theme-icarus/2018/01/01/plugin/Analytics/#Hotjar)
    hotjar:
        # Hotjar site id
        site_id: 
    # Show a loading progress bar at top of the page
    progressbar: true
# CDN provider settings
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL of the webfont CDN provider
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    iconcdn: fontawesome
